---
language: node_js
node_js:
  - "6.3.0"

sudo: false

cache:
  directories:
    - node_modules
    - bower_components

before_install:
  - npm config set spin false
  - npm install -g bower
  - bower --version
  - npm install phantomjs-prebuilt
  - phantomjs --version

install:
  - npm install
  - bower install

script:
  - npm test
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
addons:
    code_climate:
        repo_token: 66445b2ba80578646711c9f7d9fc762f0a95c37cb6d048104d10aa16da1fcaf8
